%% High-level script for pairwise estimates of friction factor.

clear
close all


%%
% -----------------------------------------------------
% ----------------- DEFINE PARAMETERS -----------------
% -----------------------------------------------------


%% Define filename of L4 data output, and directony
% and basename for QC figures

%
file_output = "pairwise_fe_allsites.mat";


%% Define pairs

% All pair sites
list_pairs = ["A01", "E05"; ...
              "E05", "A02"; ...
              "A02", "A04"; ...
              "A04", "A05"; ...
              "A05", "A06"; ...
              "A06", "A07"; ...
...
              "B01", "B03"; ...
              "B03", "B05"; ...
              "B05", "B06"; ...
              "B06", "B08"; ...
              "B08", "B09"; ...
              "B09", "B10"; ...
              "B10", "B11"; ...
              "B11", "B12"; ...
              "B12", "B13"; ...
              "B13", "B14"; ...
              "B14", "B15"; ...
              "B15", "B16"; ...
...
              "C01", "C02"; ...
              "C02", "C05"; ...
...
              "E03", "D01"; ...
              "E09", "D02"; ...
...
              "X01", "X03"; ...
              "X03", "X04"; ...
              "X04", "X05"; ...
              "X05", "X06"; ...
              "X06", "X07"; ...
              "X07", "X08"; ...
              "X08", "X09"; ...
              "X09", "X10"; ...
              "X10", "X11"; ...
              "X11", "X12"; ...
              "X12", "X13"];


%%
% ------------------------------------------------------
% --------------------- COMPUTE fe ---------------------
% ------------------------------------------------------

%% Load L4 data

%
dataL4 = load(fullfile(paper_directory(), 'data', 'level_4', 'roxsi_data_L4.mat'));
dataL4 = dataL4.dataL4;


%% Run pairwise fe calculations

%
tic
disp('--- Doing pairwise fe estimate ---')

%
[dataL4, pwdissipation] = pairwise_fe_getdatapair(dataL4, list_pairs);

%
pwdissipation = pairwise_fe_calculate(pwdissipation);

%
disp('--- done with fe ---')



%% Save pwdissipation in L5 data folder
             
%
dir_output = fullfile(paper_directory(), 'data', 'level_5');

%
disp(['--- saving L5 data file: ' char(file_output) '---'])
%
save(fullfile(dir_output, file_output), 'pwdissipation')
%
disp('--- done saving L5 file ---')   
